### ISSUE TITLE
Undefined property: stdClass::$payment_details

### ISSUE THREAD

**Issue by magefan** [MultiSafepay/Magento2Msp#43]
We've getting another issue (Magento 2.1.9). Here is a log:

```
Undefined property: stdClass::$payment_details in /app/code/MultiSafepay/Connect/Model/Connect.php on line 870

Trace:
#0 /app/code/MultiSafepay/Connect/Model/Connect.php(870): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined prope...', '/var/www/...', 870, Array)
#1 /app/code/MultiSafepay/Connect/Controller/Connect/Notification.php(86): MultiSafepay\Connect\Model\Connect->notification(Object(Magento\Sales\Model\Order))
#2 /vendor/magento/framework/App/Action/Action.php(102): MultiSafepay\Connect\Controller\Connect\Notification->execute()
#3 /vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /vendor/magento/framework/Interception/Chain/Chain.php(70): MultiSafepay\Connect\Controller\Connect\Notification\Interceptor->___callParent('dispatch', Array)
#5 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('MultiSafepay\\Co...', 'dispatch', Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Array, 'contextPlugin')
#6 /vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#8 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('MultiSafepay\\Co...', 'dispatch', Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Array, 'customer-app-ac...')
#9 /vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#10 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('MultiSafepay\\Co...', 'dispatch', Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Array, 'storeCheck')
#12 /vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('MultiSafepay\\Co...', 'dispatch', Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Array, 'weee-app-action...')
#15 /vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('MultiSafepay\\Co...', 'dispatch', Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Array, 'tax-app-action-...')
#18 /vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): MultiSafepay\Connect\Controller\Connect\Notification\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(MultiSafepay\Connect\Controller\Connect\Notification\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /var/generation/MultiSafepay/Connect/Controller/Connect/Notification/Interceptor.php(26): MultiSafepay\Connect\Controller\Connect\Notification\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /vendor/magento/framework/App/FrontController.php(55): MultiSafepay\Connect\Controller\Connect\Notification\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#24 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#25 /vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#28 /vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#31 /vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#34 /vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'Amasty_Invisibl...')
#37 /app/code/Amasty/InvisibleCaptcha/Plugin/Predispatch.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#38 /vendor/magento/framework/Interception/Interceptor.php(142): Amasty\InvisibleCaptcha\Plugin\Predispatch->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#40 /vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#41 /vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#42 /pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#43 {main}
```

Could you please provide a solution?
Best regards.

**Comment by Jasper-MultiSafepay** [comment]
@magefan 
Could you send an email to techsupport@multisafepay.com ?
We would like to investigate this further.

**Comment by magefan** [comment]
Yes, sent.

**Comment by Tristan-N** [comment]
@jasper-multisafepay Hi Jasper,

Do you have any updates on this issue? This error occurs to our Magento 2.1.8 shop, but also with the $base_price variable that seems to be unset. 

Additional: This error occurs when we try to checkout products with tier prices. As soon as the tier price is activated, the connector fails.

For example: 
product price: €10
product tier 5: €9
product tier 10: €8. 

If I order 1, 2, 3 or 4 products, everything works fine. As soon as I order 5 or more, it breaks with the same errorcode as above (sometimes with `a:4:{i:0;s:164:"Notice: Undefined property: stdClass::$base_price in ... magento2/vendor/multisafepay/magento2msp/Model/Connect.php on line 589"` 

Do you have any updates on this issue?

Thanks

**Comment by Jasper-MultiSafepay** [comment]
@Tristan-N 
Regarding issue1:
On line 865 add the following line:
if(isset($msporder->payment_details)) {
and close this on line 877 with:
}

Regarding issue2:
Replace base_price with price on lines 589 and 592
So $value->base_price becomes $value->price

We will also push these commits/fixes to GitHub, hopefully soon.
