### ISSUE TITLE
[ZAG-524-92489] Incompatibility Aheadworks_Ajaxcartpro

### ISSUE THREAD

**Issue by gijsde3de** [MultiSafepay/Magento2Msp#66]
There is an incompatibility between msp and aheadworks_ajaxcartpro 1.2.5 (latest version) and msp latest version.

Aheadworks has the following plugin:

```
<type name="Magento\Framework\App\Action\Action">
    <plugin name="ajaxcartpro-action-plugin" type="Aheadworks\Ajaxcartpro\Controller\Plugin\Action" sortOrder="1" disabled="false" />
</type>
```

This apparently breaks your multisafepay/magento2msp/Controller/Connect/Success.php with the following error.

```
a:4:{i:0;s:178:"Notice: Undefined index: MultiSafepay\Connect\Controller\Connect\Success in /data/web/magento2-staging/vendor/magento/framework/Interception/PluginList/PluginList.php on line 232";i:1;s:6559:"#0 /data/web/magento2-staging/vendor/magento/framework/Interception/PluginList/PluginList.php(232): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/data/web/magen...', 232, Array)
#1 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(74): Magento\Framework\Interception\PluginList\PluginList->getPlugin('MultiSafepay\\Co...', 'ajaxcartpro-act...')
#2 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('MultiSafepay\\Co...', 'dispatch', Object(MultiSafepay\Connect\Controller\Connect\Success\Interceptor), Array, 'weee-app-action...')
#3 /data/web/magento2-staging/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#4 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(MultiSafepay\Connect\Controller\Connect\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#5 /data/web/magento2-staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('MultiSafepay\\Co...', 'dispatch', Object(MultiSafepay\Connect\Controller\Connect\Success\Interceptor), Array, 'tax-app-action-...')
#6 /data/web/magento2-staging/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(110): MultiSafepay\Connect\Controller\Connect\Success\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /data/web/magento2-staging/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(MultiSafepay\Connect\Controller\Connect\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#8 /data/web/magento2-staging/var/generation/MultiSafepay/Connect/Controller/Connect/Success/Interceptor.php(26): MultiSafepay\Connect\Controller\Connect\Success\Interceptor->___callPlugins('dispatch', Array, Array)
#9 /data/web/magento2-staging/vendor/magento/framework/App/FrontController.php(55): MultiSafepay\Connect\Controller\Connect\Success\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /data/web/magento2-staging/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#12 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#13 /data/web/magento2-staging/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#16 /data/web/magento2-staging/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#19 /data/web/magento2-staging/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /data/web/magento2-staging/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /data/web/magento2-staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#22 /data/web/magento2-staging/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /data/web/magento2-staging/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /data/web/magento2-staging/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#25 /data/web/magento2-staging/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /data/web/magento2-staging/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#27 /data/web/magento2-staging/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#28 {main}";s:3:"url";s:54:"/multisafepay/connect/success?transactionid=1000004607";s:11:"script_name";s:10:"/index.php";}

```

**Comment by Jasper-MultiSafepay** [comment]
If you could send an email to techsupport@multisafepay.com with your staging details, we could investigate this further.

**Comment by gijsde3de** [comment]
Hey sorry for the late reaction.

url: https://acceptatie.webwinkel.vandale.nl:8443/
I'm not entirely sure if this environment is behind a IP block, if you
can't access it please send me your IP.

For now I can't yet give you any code or backend access, I'd have to ask
permission of the customer first.



*Met vriendelijke groet / Best regards,*


Gijs Kwaks
Backend Developer
Arthur van Schendelstraat 650
030 - 8200 238
www.experius.nl
Volg ons!   <https://www.facebook.com/Experius1>
<https://www.linkedin.com/company-beta/1008104>
<https://twitter.com/experiusnl>
